config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  root to: 'pages#home'

  resources :trips do
    resources :cities, only: :index do
      resources :trip_activities, only: :show
      put '/trip_activities/:id', to: 'trip_activities#update_trip', as: 'update_trip'
    end
    resources :requests, only: :create
    resources :favorite_itineraries, only: [:create, :destroy]
    resources :messages, only: :create
  end

  resources :itineraries, only: [:show, :index]
  resources :user_activities, only: [:create, :update]
  resources :follows, only: [:create, :destroy, :index]
  resources :invitations, only: :create
end

app/models/trip.rb
class Trip < ApplicationRecord
  belongs_to :user
  belongs_to :city, optional: true
  belongs_to :user_activity, optional: true
  has_many :participants, dependent: :destroy
  has_many :users, through: :participants, dependent: :destroy
  has_many :favorite_itineraries, dependent: :destroy
  has_many :itineraries, through: :favorite_itineraries, dependent: :destroy
  has_many :trip_activities, dependent: :destroy
  has_many :invitations, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_one :trip_activity, dependent: :destroy
  attribute :validated, default: false
  validates :start_date, presence: true
  validates :end_date, presence: true
  geocoded_by :location, latitude: :coord_lat, longitude: :coord_long
  after_validation :geocode, if: :will_save_change_to_location?

  def validated?
    validated
  end

  def duration
    self.start_date.upto(self.end_date).to_a.size
  end

  def short_address
    self.location.split(" ")[0].gsub(",", "")
  end

  def short_start_date
    "#{start_date.to_s[-2..-1]} / #{start_date.to_s[-5..-4]}"
  end

end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :store_invitation_token
  before_action :empty_top_cities
  before_action :authenticate_user!, only: :show
  before_action :check_that_user_is_participant, only: :show

  def new
    @user_activities = current_or_guest_user.user_activities
                                            .where.not(activity_id: Activity.expert_activities)
    @trip = Trip.new
  end

  def show
    trip = Trip.find(params[:id])

    if trip.validated?
      redirect_to trip_city_trip_activity_path(trip, trip.city, trip.trip_activity)
    else
      redirect_back(fallback_location: root_path)
    end
  end

  def index
    @trips = current_or_guest_user.trips.reverse
  end

  def create
    dates_to_eng(params)
    @trip = Trip.new(trip_params)
    @trip.user = current_or_guest_user
    @trip.save!

    # Add current user as participant to the trip
    Participant.create!(user: current_or_guest_user, trip: @trip)

    # Create trip_activities so that if the user changes its profile it wont change the results
    current_or_guest_user.user_activities.where.not(level: nil).each do |user_activity|
      TripActivity.create!(trip: @trip, activity: user_activity.activity, level: user_activity.level)
    end

    redirect_to trip_cities_path(@trip)
  end

  def destroy
    trip = Trip.find(params[:id])
    trip.destroy
    flash[:notice] = "La sortie a été supprimée."
    redirect_back(fallback_location: root_path)
  end

  private

  def trip_params
    params.require(:trip).permit(:start_date, :end_date, :location, :validated)
  end

  def store_invitation_token
    session[:invitation_token] = params[:invitation_token]
  end

  def check_that_user_is_participant
    trip = Trip.find(params[:id])

    unless trip.users.include?(current_user)
      flash[:alert] = "Tu n'es pas invité sur cette sortie."
      redirect_to root_path
    end
  end

  # Some logic to allow french langage within the calendar

  FR_TO_EN = [%w[Janvier January],
              %w[Février February],
              %w[Mars March],
              %w[Avril April],
              %w[Mai May],
              %w[Juin June],
              %w[Juillet July],
              %w[Août August],
              %w[Septembre September],
              %w[Octobre October],
              %w[Novembre November],
              %w[Décembre December],
              %w[Dim Sun],
              %w[Lun Mon],
              %w[Mar Tue],
              %w[Mer Wed],
              %w[Jeu Thu],
              %w[Ven Fri],
              %w[Sam Sat]]

  def date_to_eng(fr_stringified_date)
    eng_date = fr_stringified_date.split(' ').map! do |word|
      if word[0].match?(/[a-zA-Z]/)
        FR_TO_EN.select { |coupled_array| coupled_array[0] == word }[0][1]
      else word
      end
    end
    eng_date.join(' ')
  end

  def dates_to_eng(params)
    params[:trip][:start_date] = date_to_eng(params[:trip][:start_date])
    params[:trip][:end_date] = date_to_eng(params[:trip][:end_date])
    params
  end

  def empty_top_cities
    session[:cities_activities] = nil
  end
end

app/views/trips/index.html.erb
<br>
<div class="container">
  <div class="row">

    <% @trips.each do |trip| %>
    <div class="col s12 m12 l6">
    <div class="card horizontal card-trip">
      <div class="card-image">
        <img src="https://res.cloudinary.com/deesjjv4h/image/upload/v1552047840/crux/images/tripImageF.jpg">
      </div>
        <div class="card-stacked">
          <div class="card-content">
            <p class="title-card" style="font-weight: 500;">Sortie du <%= l trip.start_date, :format => :long %> au <%= l trip.end_date, :format => :long %></p>
            <br>
            <p><i class="fas fa-car"></i> depuis <%= trip.location.split(",")[0] %> </p>
          </div>
          <div class="card-action">
            <% if trip.validated %>
            <%= link_to 'Voir', trip_city_trip_activity_path(trip, trip.city, trip.trip_activity), class: 'green-link' %>
            <% else %>
              <%= link_to 'Finir la séléction', trip_cities_path(trip), class: 'green-link' %>
            <% end %>
            <%= link_to "", trip_path(trip), method: :delete, class: 'fas fa-trash add-itinerary' %>
          </div>
        </div>
      </div>
    </div>
    <% end %>

    </div>
  </div>
</div>

app/views/trips/new.html.erb
<div class="container">
  <div class="row">
    <div class="col s12 m6 offset-m3">

      <h5 class="form-title">Sélectionne une ou des activités</h5>

      <% @user_activities.each do |user_activity| %>
        <div class="col s3">
            <%= image_tag "icons/#{user_activity.activity.name}.png", class: "circle responsive-img small icon-source #{'selected-icon' if user_activity.set?}", id: user_activity.activity.name %>
        </div>
      <% end %>

      <% @user_activities.each do |user_activity| %>

        <div class="input-field col s12 m6 icon-target <%= 'hidden' if user_activity.level == nil %>" id=<%= user_activity.activity.name %>>
          <%= simple_form_for user_activity, remote: true, data: { turbolinks: false }  do |f| %>
            <%= f.input :level, collection: ["Niveau ?", "Débutant","Intermédiaire","Expérimenté"], label: user_activity.activity.short_name.capitalize, input_html: { class: user_activity.activity.name.split(" ")[0]},include_blank: false, include_hidden: false %>
            <%= f.hidden_field  :activity_id %>
          <% end %>
        </div>
      <% end %>

      <h5 class="form-title col s12 m12 no-padding">Dis-nous d'où et quand tu pars</h5>
      <div class="input-field col s12 m12">
        <%= simple_form_for @trip do |f| %>
          <%= f.input  :location, input_html: { id: "trip_address", placeholder: "Ville de départ (Lyon, Paris...)"}, label: false %>
          <div style="display: flex">
            <%= f.input  :start_date, as: :string, input_html: { class: 'datepicker datepicker-start', placeholder: "Date de départ"}, label: false %>
            <%= f.input  :end_date, as: :string, input_html: { class: 'datepicker datepicker-end', placeholder: "Date de fin"}, label: false %>
          </div>
          <div id="empty-field-message" class="transparent">
            <p class ="center-align">Ces champs ne peuvent pas être vides.</p>
          </div>
          <div class="center-align">
            <input type="submit" value="Dis-moi où partir" class="waves-light btn-large" id="letsGoBtn">
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>


<div class="curtain col s12">
  <div class="curtain-content center-align">
    <img src="https://res.cloudinary.com/dbehokgcg/image/upload/v1553600239/crux-boussole.png" class="boussole">
    <ul class="list" style="font-size: 1.64em !important;">
      <li id="row-intro" class="font-monospace"><strong>Crux</strong> analyse les conditions en montagne :</li>
      <li class="transparent" id="row-iti" class="font-monospace"><strong><span id="itinerary-count"> <%= Itinerary.count %> </span> itinéraires...</strong></li>
      <li class="transparent" id="row-basecamp"class="font-monospace"><strong> <span id="basecamp-count"><%=  Basecamp.count %></span> camps de base...</strong></li>
      <li class="transparent" id="row-weather"class="font-monospace"><strong><span id="weather-count"><%=  Weather.count * 2 %></span> bulletins météo...</strong></li>
    </ul>
  </div>
</div>

app/views/trips/show.html.erb
<div class="container basecamps-activities-container"  data-ors-api-key="<%= ENV['OPENROUTE_API_KEY2'] %>">
  <h3>Choisis ton camp de base</h3>
  <div class="row">

  <% @basecamps_activities.each do |base| %>
    <div class="col s12 m4">
      <h4 class="header"><%= base.basecamp.name.encode("iso-8859-1").force_encoding("utf-8")%></h4>
      <div class="card card-basecamp-activity horizontal small">
        <div class="card-image">
          <% if base.activity.name == "ski de randonnée" %>

          <% elsif base.activity.name == "alpinisme" %>
            <%= image_tag "alpi.jpg" %>
          <% elsif base.activity.name == "escalade" %>
            <%= image_tag "escalade.jpg" %>
          <% end %>
        </div>
        <div class="card-stacked">
          <div class="card-content" data-coords="<%= { ori_lat: @trip.coord_lat, ori_long: @trip.coord_long, desti_lat: base.basecamp.coord_lat, desti_long: base.basecamp.coord_long }.to_json %>">
            <h4><%= base.activity.name.capitalize.split(" ")[0] %></h4>
            <br>
            <p><strong><%= base.nb_itineraries %></strong> itinéraires</p>
            <br>
            <p id="driving-time"></p>
            <br>
            <p><img src="<%= "http:" + base.basecamp.weather.forecast[0]["day"]["condition"]["icon"].to_s %>" style="width: 32px; height: 32px;"> <%= base.basecamp.weather.forecast[0]["day"]["avgtemp_c"].to_s.gsub(".", ",") %>°C</p>
          </div>
          <div class="card-action">
            <div class="left-align">
              <%= link_to "Go !", basecamps_activity_path(base), class: "waves-effect waves-light btn" %>
              <button class="waves-effect waves-light btn secondary">+</button>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>

  </div>
</div>