config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  root to: 'pages#home'

  resources :trips do
    resources :cities, only: :index do
      resources :trip_activities, only: :show
      put '/trip_activities/:id', to: 'trip_activities#update_trip', as: 'update_trip'
    end
    resources :requests, only: :create
    resources :favorite_itineraries, only: [:create, :destroy]
    resources :messages, only: :create
  end

  resources :itineraries, only: [:show, :index]
  resources :user_activities, only: [:create, :update]
  resources :follows, only: [:create, :destroy, :index]
  resources :invitations, only: :create
end

app/models/trip_activity.rb
class TripActivity < ApplicationRecord
  belongs_to :trip, optional: true
  belongs_to :activity
end

app/controllers/trip_activities_controller.rb
class TripActivitiesController < ApplicationController
  before_action :init_mark_down_parser, only: :show
  before_action :get_trip_and_city

  def show
    @trip_activity = TripActivity.find(params[:id])
    @activity = Activity.find(@trip_activity.activity_id)
    @mountain_range = @city.mountain_range
    @favorite_itinerary = FavoriteItinerary.new
    @invitation = Invitation.new
    @message = Message.new

    if params[:query].present? && !params[:query].blank?
      @itineraries = Itinerary.where("name ILIKE ?", "%#{params[:query]}%")[0..10]
      respond_to do |format|
        format.js { render partial: 'shared/search-results', locals: {search_result_itineraries: @itineraries, favorite: @favorite_itinerary, trip: @trip, follow: nil, followed_itineraries: nil, user: nil}}
      end
    elsif @trip.validated
      @itineraries = @trip.itineraries.distinct.order(picture_url: :asc)
    else
      @itineraries = @city.itineraries.where(activity_id: @activity.id, universal_difficulty: @trip_activity.level.downcase)
    end

    @itineraries = @itineraries.to_a.sort_by { |itinerary| itinerary.score}.reverse

    # Mapbox
    @markers = @itineraries.map do |itinerary|
      {
        lng: itinerary.coord_long,
        lat: itinerary.coord_lat,
        infoWindow: render_to_string(partial: "info_iti", locals: { itinerary: itinerary }),
        image_url: helpers.asset_url('https://cdn.iconscout.com/icon/premium/png-256-thumb/mountain-233-793712.png')
      }
    end
  end

  def update_trip
    redirect_to new_user_registration_path and return if current_user.nil?
    trip_activity = TripActivity.find(params[:id])

    if @trip.validated
      @trip.validated = false
    else
      @trip.validated = true
      @trip.city = @city
      @trip.trip_activity = trip_activity
    end

    @trip.save!

    flash[:notice] = "Tes itinéraires sont sauvegardés, directement accessibles depuis 'Mes sorties'" if @trip.validated
    redirect_back(fallback_location: root_path)
  end

  private

  def user_activity_params
    params.require(:user_activity).permit(:level, :activity_id)
  end

  def get_trip_and_city
    @trip = Trip.find(params[:trip_id])
    @city = City.find(params[:city_id])
  end
end

app/views/trip_activities/_avalanche_infos.html.erb
<div class=" trip-tab">
  <h5 class= "trip-tab-infos light-padding"><%= @mountain_range.name %> - Estimation du risque d'avalanche</h5>
  <p id="bra-date">Date du dernier bulletin BRA :<em style="font-weight:bold;"> <%= @mountain_range.bra_date.strftime("%d/%m/%Y") %></em></p>

    <%= image_tag(@mountain_range.rosace_url.split("/")[-1], class: "materialboxed scale-down")%>
      <ul id="legend">Indices de risque : <li>1 faible - 2 limité - 3 marqué</li><li> - 4 fort - 5 très fort</li></ul>
      <figcaption>En noir : les pentes les plus dangereuses</figcaption>

  <h5 class= "trip-tab-infos"><strong>Stabilité du manteau neigeux</strong></h5>
  <p class="trip-tab-infos text-justify"> <%= @mountain_range.stability %></p>
  <h5 class= "trip-tab-infos"><strong>Qualité de la neige</strong></h5>
  <p class="trip-tab-infos text-justify"> <%= @mountain_range.snow_quality %></p>
  <div class = " trip-tab-infos">
  <div class="row">
    <div class="col s12 m6">
        <%= image_tag(@mountain_range.snow_image_url.split("/")[-1], class: "materialboxed scale-down")%>
        <figcaption>Epaisseur de neige hors-piste</figcaption>
    </div>
    <div class="col s12 m6">
        <%= image_tag(@mountain_range.fresh_snow_url.split("/")[-1], class: "materialboxed scale-down")%>
        <figcaption>Neige Fraîche à 1800m</figcaption>
    </div>
  </div>
  </div>
</div>

app/views/trip_activities/_info_iti.html.erb
<p><%= itinerary.name %></p>
<%= link_to "Plus d'infos...", itinerary_path(itinerary), class: "green-link" %>

app/views/trip_activities/_mapbox.html.erb
<div
  id="map"
  style="
  height: 600px;"
  data-markers="<%= @markers.to_json %>";
  data-polygon="<%= @one_hour_polygon.to_json %>";
  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>";>
</div>

app/views/trip_activities/_participants.html.erb
<div class="trip-tab light-padding light-margin">
  <h6 class="strong">Participants actuels</h6>
  <ul>
    <% participants.each do |participant| %>
    <li>
      <%= participant.user.email %>
    </li>
    <% end %>
  </ul>
</div>

<div class=" trip-tab light-padding light-margin">
  <h6 class="strong">Invite tes compagnons</h6>
  <div class="form-container flexbox-class">
    <%= simple_form_for @invitation, html: {:class => "form-inline"} do |f| %>

    <div class="flexbox-class">
      <%= f.input  :mailed_to, label: false, placeholder: "reihnold@messner.com" %>
      <%= f.input  :trip_id, input_html: {value: @trip.id}, as: :hidden %>
      <%= f.button :submit, "Inviter", class: 'btn' %>
    </div>
    <% end %>
  </div>
</div>

<div class=" trip-tab light-padding light-margin">
  <h6 class="strong">Papotez</h6>
  <div class="chat" data-channel-subscribe="trip" data-trip-id="<%= @trip.id %>">
    <ul>
      <% @trip_activity.trip.messages.each do |message| %>
        <li>
          <em><%= message.content %></em> dit <%= message.user.email %>
        </li>
      <% end %>
    </ul>
  </div>

  <%= simple_form_for [@trip, @message], remote: true do |form| %>
    <div class="flexbox-class">
      <%= form.input :content, as: :string,
                               wrapper: false,
                               label: false,
                               input_html: {
                                 class: 'chat-input'
                               } %>
      <%= form.submit "Send", class: 'btn btn-primary chat-input' %>
    </div>
  <% end %>
</div>

<div class="d-none" data-role="message-template">
  <div class="chat-message-container">
    <div class="row no-gutters">
      <div class="col-auto text-center">
        <img src="" class="avatar" alt="" data-role="user-avatar">
      </div>

      <div class="col">
        <div class="message-content">
          <p class="mb-1" data-role="message-text"></p>

          <div class="text-right">
            <small data-role="message-date"></small>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/trip_activities/_tabs.html.erb
<ul class="tabs tabs-fixed-width">
  <li class="tab col s1">
    <a class="active" href="#itineraries">
      <span class="hide-on-small-only">Itinéraires</span>
      <span class="hide-on-med-and-up"><i class="fas fa-route bigger"></i></span>
    </a>
  </li>
  <li class="tab col s1">
    <a class="" href="#weather">
      <span class="hide-on-small-only">Météo</span>
      <span class="hide-on-med-and-up"><i class="fas fa-cloud-sun bigger"></i></span>
    </a>
  </li>
  <li class="tab col s1">
    <a class="" href="#avalanche">
      <span class="hide-on-small-only">Avalanche</span>
      <span class="hide-on-med-and-up"><i class="fas fa-exclamation-triangle bigger"></i></span>
    </a>
  </li>
  <li class="tab col s1">
    <a class="" href="#map-ba">
      <span class="hide-on-small-only">Carte</span>
      <span class="hide-on-med-and-up"><i class="fas fa-map-marked bigger"></i></span>
    </a>
  </li>
  <% if @trip.validated?  %>

  <li class="tab col s1">
    <a class="" href="#participants">
      <span class="hide-on-small-only">Participants</span>
      <span class="hide-on-med-and-up"><i class="fas fa-user bigger"></i></span>
    </a>
  </li>

  <% end %>
</ul>

app/views/trip_activities/_trip_validation.html.erb
<div class="right-align" id="favorite">
  <% if trip.validated%>
    <%= link_to "", trip_favorite_itinerary_path(trip, itinerary), method: :delete, class: 'fas fa-trash add-itinerary' %>
  <% else %>

    <% if trip.itineraries.distinct.include?(itinerary) %>
      <a class="fas fa-mountain add-itinerary"></a>
    <% else %>
      <a onclick="M.toast({html: 'Itinéraire ajouté', classes: 'toaster', displayLength: 500})" class="fas fa-plus-circle add-itinerary"></a>
    <% end %>

    <%= simple_form_for [trip, favorite], remote: true do |f| %>
    <%= f.input  :trip_id, input_html: {value: trip.id} %>
    <%= f.input  :itinerary_id, input_html: {value: itinerary.id} %>
    <% end %>

  <% end %>
</div>

app/views/trip_activities/_weather_infos.html.erb
<div class="trip-tab">
  <h5 class="trip-tab-infos light-padding">Météogramme</h5>
  <%= image_tag(@city.meteoblue_semaine_url, class: "materialboxed")%>
</div>

app/views/trip_activities/show.html.erb
<div class="container">

  <div class="ellipsis center-align strong" style="margin-top: 15px;">
    <% if @trip.validated == false %>
      <%= link_to "", trip_cities_path(@trip), class: "fas fa-chevron-circle-left" %>
    <% end %>
    <%= @activity.short_name.capitalize %> à <%= @city.clean_name %>
  </div>

  <% if @trip.validated == false %>
    <div class="fixed-action-btn card-panel sticky-cta", id="validation-basecamp-button">
      <%= link_to "Valider la séléction", trip_city_update_trip_path(@trip, @city, @trip_activity), method: :put, class: 'btn' %>
    </div>
  <% else %>
    <div class="fixed-action-btn card-panel sticky-cta">
      <%= link_to "Ajouter des itinéraires", trip_city_update_trip_path(@trip, @city, @trip_activity), method: :put, class: 'btn blue' %>
    </div>
  <% end %>

  <div class="row">
    <div class="col s12">

      <%= render partial: "tabs" %>

      <div id="itineraries" style="margin: 10px;">

        <% if @trip.validated == false %>

            <div class="left-align font-1em">Choisis parmi <%= @itineraries.count %> itinéraires proches
              <%= form_tag(trip_city_trip_activity_path(@trip, @city, @trip_activity), method: :get, remote: true) do %>
                <%= text_field_tag :query,
                  params[:query],
                  class: "form-control left-align font-1em smaller-width",
                  placeholder: "ou toute la base (e.g. \"whymper\")"
                %>
                <i class="fas fa-search" id="green-search"></i>
              <% end %>
            </div>

        <% end %>

        <div class="slide-container">

          <div id="search-results">
          </div>
          <% @itineraries.each do |itinerary| %>
          <% next if itinerary.name.nil? || itinerary.universal_difficulty.nil? %>
          <%= render partial: "shared/card_itinerary", locals: {itinerary: itinerary, favorite: @favorite_itinerary, trip: @trip} %>
          <% end %>
        </div>

      </div>

      <div id="weather">
        <div class="row">
          <%= render partial: "weather_infos" %>
        </div>
      </div>
      <% if @mountain_range %>
      <div id="avalanche">
        <div class="row">
          <%= render partial: "avalanche_infos" %>
        </div>
      </div>
      <% end %>
      <div id="map-ba">
        <div class="row" id="content-map">
          <%= render partial: "mapbox" %>
        </div>
      </div>

      <% if @trip.validated %>
      <div id="participants">
        <div class="row">
          <%= render partial: "participants", locals: {participants: @trip_activity.trip.participants} %>
        </div>
      </div>
      <% end %>

    </div>
  </div>
</div>