config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  root to: 'pages#home'

  resources :trips do
    resources :cities, only: :index do
      resources :trip_activities, only: :show
      put '/trip_activities/:id', to: 'trip_activities#update_trip', as: 'update_trip'
    end
    resources :requests, only: :create
    resources :favorite_itineraries, only: [:create, :destroy]
    resources :messages, only: :create
  end

  resources :itineraries, only: [:show, :index]
  resources :user_activities, only: [:create, :update]
  resources :follows, only: [:create, :destroy, :index]
  resources :invitations, only: :create
end

app/views/shared/_card_itinerary.html.erb
<div class="col s12 m6">
  <div class="card small">

    <div class="card-image waves-effect waves-block waves-light">
      <img class="activator cover" src="<%= itinerary.picture_url_p %>">
    </div>

    <div class="card-content">
      <p>
        <div class="title-card ellsipsised card-title activator grey-text text-darken-4">
          <% if itinerary.score > 0.8 %>
            <span class="strong-card-title"><%= itinerary.short_name %> <i class="fas fa-heart"></i></span>
          <% elsif itinerary.score > 0 %>
            <span class="strong-card-title" style="font-weight: lighter;"><%= itinerary.short_name %></span>
          <% else %>
            <span><%= itinerary.short_name %></span>
          <% end %>
        </div>

        <hr />

        <div class="center-align">
          <% if itinerary.elevation_max != nil  %>
            <span class="tertiary tooltipped" data-position="bottom" data-tooltip="Altitude max"><%= itinerary.elevation_max %>m</span>
          <% end %>
          <% if itinerary.height_diff_up != nil%>
            <span class="tertiary tooltipped" data-position="bottom" data-tooltip="Dénivelé positif">+ <%= itinerary.height_diff_up %> m</span>
          <% end %>
          <span class="tertiary tooltipped" data-position="bottom" data-tooltip="Difficulté"><%= itinerary.difficulty %></span>
          <span class="tertiary tooltipped" data-position="bottom" data-tooltip="Equipement"><%= itinerary.equipment_rating %></span>
          <span class="tertiary tooltipped" data-position="bottom" data-tooltip="Engagement"><%= itinerary.engagement_rating %></span>
        </div>

        <hr />

        <%= render partial: "shared/outing_months", locals: {itinerary: itinerary} %>

        <% if defined?(trip) && !trip.nil? %>
          <%= render partial: "trip_validation", locals: {itinerary: itinerary, favorite: favorite, trip: trip} %>
        <% elsif defined?(follow) && !follow.nil? %>
          <%= render partial: "shared/follow_validation", locals: {itinerary: itinerary, follow: follow, followed_itineraries: followed_itineraries, user: user} %>
        <% end %>

      </p>
    </div>

    <div class="card-reveal">
      <p class="card-title grey-text text-darken-4"><strong><%= itinerary.name %></strong><i class="material-icons right absolute">close</i></p>
      <p><%= render partial: "shared/itinerary_description", locals: {itinerary: itinerary} %></p>
    </div>

  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="row-no-margin-bottom" id="alert_box">
    <div class="col s12 m12">
      <div class="card alert-info alert-dismissible darken-1" style="margin: 0px">
        <div class="row row-no-padding-top" style="margin: 0px">
          <div class="col s12 m10 offset-m1">
            <div class="card-content white-text font-alert" style="text-align: center;">
              <%= notice %>
            </div>
          </div>
        <div class="col s12 m2">
          <i class="fa fa-times icon_style" id="alert_close" aria-hidden="true"></i>
        </div>
      </div>
     </div>
    </div>
  </div>
<% end %>

<% if alert %>
  <div class="row-no-margin-bottom" id="alert_box">
    <div class="col s12 m12">
      <div class="card alert-warning alert-dismissible darken-1" style="margin: 0px">
        <div class="row row-no-padding-top" style="margin: 0px">
          <div class="col s12 m10 offset-m1">
            <div class="card-content white-text font-alert" style="text-align: center;">
              <%= alert %>
            </div>
          </div>
        <div class="col s12 m2">
          <i class="fa fa-times icon_style" id="alert_close" aria-hidden="true"></i>
        </div>
      </div>
     </div>
    </div>
  </div>
<% end %>

app/views/shared/_follow_validation.html.erb
<div class="right-align" id="favorite">

  <% if followed_itineraries.include?(itinerary)%>
  <% followed_itinerary = Follow.find_by(user: user, itinerary: itinerary) %>
    <%= link_to "", follow_path(followed_itinerary), method: :delete, class: 'fas fa-trash add-itinerary' %>
  <% else %>
    <a onclick="M.toast({html: 'Itinéraire suivi', classes: 'toaster', displayLength: 500})" class="fas fa-plus-circle add-itinerary"></a>
  <% end %>

  <%= simple_form_for follow, remote: true, html: { class: "hidden"} do |f| %>
    <%= f.input  :user_id, input_html: {value: user.id} %>
    <%= f.input  :itinerary_id, input_html: {value: itinerary.id} %>
  <% end %>

</div>

app/views/shared/_footer.html.erb
<footer class="page-footer">
  <div class="footer-copyright">
    <div class="container">
    © 2019 Copyright Crux
        <a class="grey-text text-lighten-4 right "  href="#!"><i class="fab fa-github"></i></a>
        <a class="grey-text text-lighten-4 right "  href="#!"><i class="fab fa-instagram"></i></a>
        <a class="grey-text text-lighten-4 right "  href="#!"><i class="fab fa-facebook"></i></a>
    </div>
  </div>
</footer>

app/views/shared/_itinerary_description.html.erb
<% if itinerary.content %>

  <div id="itinerary-content">
    <%= link_to 'Topo détaillé', itinerary_path(itinerary), class: "green-link" %>
    <%= @markdown.render(itinerary.clean_content).html_safe %>
  </div>

<% end %>

app/views/shared/_navbar.html.erb
<nav>
  <div class="nav-wrapper">
    <%= link_to "#{image_tag('https://res.cloudinary.com/dzxrdf9za/image/upload/v1551869936/Cruxlogosquarebig.jpg', class: "small-image")} Crux".html_safe, root_path, class: "brand-logo no-hover logo-with-text logo-box" %>
    <a href="#" data-target="mobile-menu" class="sidenav-trigger"><i class="material-icons">menu</i></a>
    <ul class="right hide-on-med-and-down">
      <% if user_signed_in? %>
        <li><%= link_to "Mes sorties", trips_path, class: "" %></li>
        <li><%= link_to "Nouvelle sortie", new_trip_path, class: "" %></li>
        <li><%= link_to "Itinéraires", itineraries_path %></li>
        <li><%= link_to "Favoris", follows_path %></li>
        <li><%= link_to "Se déconnecter", destroy_user_session_path, :method => :delete %></li>
      <% else %>
        <li><%= link_to "Nouvelle sortie", new_trip_path, class: "" %></li>
        <li><%= link_to "Se connecter", new_user_session_path %></li>
      <% end %>
    </ul>
  </div>
</nav>

<ul class="sidenav" id="mobile-menu">
  <%= link_to root_path do %>
    <div class="side-bar-head center-align">
      <%= image_tag('https://res.cloudinary.com/dzxrdf9za/image/upload/v1551869936/Cruxlogosquarebig.jpg', class: "medium-image") %>
      <h5 class="center-align black-font" style="margin-top: 0px">Crux</h5>
    </div>
  <% end %>
  <% if user_signed_in? %>
    <li><%= link_to "Mes sorties", trips_path, class: "" %></li>
    <li><%= link_to "Nouvelle sortie", new_trip_path, class: "" %></li>
    <li><%= link_to "Itinéraires", itineraries_path %></li>
    <li><%= link_to "Favoris", follows_path %></li>
    <li><%= link_to "Se déconnecter", destroy_user_session_path, :method => :delete %></li>
  <% else %>
    <li><%= link_to "Nouvelle sortie", new_trip_path, class: "" %></li>
    <li><%= link_to "Se connecter", new_user_session_path %></li>
  <% end %>
</ul>

app/views/shared/_navbar_back.html.erb
<nav>
  <div class="nav-wrapper">
    <div class="container">
      <%= link_to "Crux", root_path, class: "brand-logo" %>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <% if user_signed_in? %>
          <li><%= link_to "Mes sorties", trips_path %></li>
          <li><%= link_to "Profil", edit_user_registration_path %></li>
          <li><%= link_to "Se déconnecter", destroy_user_session_path, :method => :delete %></li>
        <% else %>
          <li> <%= link_to "Se connecter", new_user_session_path %> </li>
        <% end %>
      </ul>
    </div>
    <div class="navbar-crux-item hidden-md hidden-lg">
      <div class="dropdown right">
        <a class='dropdown-trigger' href='#' data-target='dropdown1'>
          <i id="burger-menu" class="fas fa-bars dropdown-toggle"></i></a>
        <ul id='dropdown1' class="dropdown-menu dropdown-menu-right navbar-crux-dropdown-menu">
          <% if user_signed_in? %>
            <li><%= link_to "Mes sorties", trips_path %></li>
            <li><%= link_to "Profil", edit_user_registration_path %></li>
            <li><%= link_to "Se déconnecter", destroy_user_session_path, :method => :delete %></li>
          <% else %>

            <li> <%= link_to "Se connecter", new_user_session_path %> </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</nav>

app/views/shared/_outing_months.html.erb
<div class="center-align outings-calendar">
  <span class="calendar-title">
      Mois préférés
  </span>
  <span class="calendar-months">
    <% itinerary.guessed_outing_months.each_with_index do |count, index| %>
      <% if count == 0 %>
        <span class="case">
      <% elsif count == 1 %>
        <span class="blue-case">
      <% else %>
        <span class="strong-blue-case">
      <% end %>
      <%= index + 1 %>
        </span>
    <% end %>
  </span>

</div>

app/views/shared/_results.html.erb
<% search_result_itineraries.each do |itinerary| %>
  <% next if itinerary.name.nil? || itinerary.universal_difficulty.nil? %>
  <%= render partial: "shared/card_itinerary", locals: {itinerary: itinerary, favorite: favorite, trip: trip,
      follow: follow, followed_itineraries: followed_itineraries, user: user} %>
<% end %>

app/views/shared/_search-results.js.erb
$("#search-results").html("<%= escape_javascript(render partial: 'shared/results', locals: {search_result_itineraries: search_result_itineraries, favorite: favorite, trip: trip, follow: follow, followed_itineraries: followed_itineraries, user: user}) %>");

var favoritesInModal = document.querySelectorAll('.fa-plus-circle');
favoritesInModal.forEach( (element) => {
  element.addEventListener('click', (e) => {
    console.log(e.currentTarget.nextElementSibling);
    Rails.fire(e.currentTarget.nextElementSibling, 'submit')
  });
});

var addButtonInModal = document.querySelectorAll('.fa-plus-circle')
addButtonInModal.forEach( (element) => {
  element.addEventListener('click', (e) => {
    e.currentTarget.closest('.card').classList.add('selected');
    e.currentTarget.classList.add('fa-mountain');
    e.currentTarget.classList.remove('fa-plus-circle');
  });
});